import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type Language = 'en' | 'am' | 'om';
export type ThemeMode = 'light' | 'dark';

const translations = {
  en: {
    nav: {
      dashboard: 'Dashboard',
      analytics: 'Analytics',
      operators: 'Operators',
      callLogs: 'Call Logs',
      rides: 'Rides',
      drivers: 'Drivers',
      coupons: 'Coupons',
      settings: 'Settings',
    },
    auth: {
      welcome: 'Welcome to TEKUMMA',
      description: 'Sign in to access the dispatch system',
      login: 'Login',
      loggingIn: 'Logging in...',
      operator: 'Operator',
      admin: 'Administrator',
      email: 'Email',
      password: 'Password',
      selectRole: 'Login as',
      fillAll: 'Please fill in all fields',
      loginSuccessful: 'Login successful as',
      code: 'Authentication code',
      verify: 'Verify',
      verifying: 'Verifying…',
      backToSignIn: '← Back to sign in',
      twoFactorPrompt: 'Enter your two-factor authentication code',
      invalidCode: 'Invalid code — try again.',
      enterCode: 'Enter the 6-digit code from your authenticator app.',
    },
    common: {
      logout: 'Logout',
      notifications: 'Notifications',
      profile: 'Profile',
      account: 'My Account',
      viewDetails: 'View Details',
      adminBadge: 'Admin',
      callCenter: 'Call Center',
      saveChanges: 'Save Changes',
      cancel: 'Cancel',
      addNew: 'Add New',
      search: 'Search',
      language: 'Language',
      theme: 'Theme',
      darkMode: 'Dark Mode',
      lightMode: 'Light Mode',
      optional: 'Optional',
    },
    dashboard: {
      newRide: 'New Ride',
      pendingRides: 'Pending Rides',
      activeRides: 'Active Rides',
      driverStatus: 'Driver Status',
      available: 'Available',
      busy: 'Busy',
      offline: 'Offline',
      live: 'Live',
      track: 'Track',
      assign: 'Assign',
      reNotifyDrivers: 'Re-notify Drivers',
      noPendingRides: 'No pending rides',
      noActiveRides: 'No active rides',
      noAvailableDrivers: 'No available drivers',
      viewDetails: 'View Details',
      assignDriverTo: 'Assign Driver to {0}',
      logCall: 'Log Call',
      logCallTitle: 'Log a Call',
      customerPhone: 'Customer Phone *',
      customerName: 'Customer Name',
      durationMinutes: 'Duration (minutes)',
      outcome: 'Outcome',
      completed: 'Completed',
      missed: 'Missed',
      abandoned: 'Abandoned',
      notes: 'Notes',
      saveCall: 'Save Call',
      leaveBlankForGuest: 'Leave blank for Guest',
      setPickup: 'Set Pickup',
      setDestination: 'Set Destination',
      searchPickup: 'Search pickup...',
      searchDestination: 'Search destination...',
      settingPickup: 'Setting pickup',
      settingDestination: 'Setting destination',
      unassigned: 'Unassigned',
      guest: 'Guest',
      callTest: 'Call Test',
      testCustomer: 'Test Customer',
    },
    drivers: {
      title: 'Driver Management',
      subtitle: 'Manage your driver fleet',
      searchPlaceholder: 'Search by Name, Phone, Vehicle, License Plate...',
      addButton: 'Add New Driver',
      addTitle: 'Add New Driver',
      fullName: 'Full Name *',
      phone: 'Phone Number',
      email: 'Email *',
      vehicleType: 'Vehicle Type',
      vehicleModel: 'Vehicle Model',
      licensePlate: 'License Plate',
      licenseNumber: 'License Number *',
      initialCouponBalance: 'Initial Coupon Balance',
      save: 'Add Driver',
      edit: 'Edit Driver',
      update: 'Update Driver',
      viewProfile: 'View Profile',
      editSuccess: 'Driver updated successfully!',
      createSuccess: 'Driver added successfully!',
      fillFields: 'Please fill in all required fields',
      driverName: 'Driver Name',
      vehicle: 'Vehicle Model',
      couponBalance: 'Initial Coupon Balance',
      totalDrivers: 'Total Drivers',
      available: 'Available',
      busy: 'Busy',
      noDrivers: 'No drivers found',
    },
    callLogs: {
      title: 'Call Logs',
      subtitle: 'Detailed history of all customer calls',
      logCall: 'Log Call',
      totalCalls: 'Total Calls',
      completed: 'Completed',
      missed: 'Missed',
      abandoned: 'Abandoned',
      avgDuration: 'Avg Duration',
      searchPlaceholder: 'Search by customer, phone, or operator…',
      allStatus: 'All Status',
      history: 'Call History',
      time: 'Time',
      customer: 'Customer',
      phone: 'Phone',
      operator: 'Operator',
      status: 'Status',
      duration: 'Duration',
      rideId: 'Ride ID',
      notes: 'Notes',
      noLogs: 'No call logs found',
    },
    analytics: {
      title: 'Analytics & Reports',
      subtitle: 'Overview of dispatch performance',
      today: 'Today',
      week: 'This Week',
      month: 'This Month',
      year: 'This Year',
      totalRides: 'Total Rides',
      totalRevenue: 'Total Revenue',
      activeDrivers: 'Active Drivers',
      totalCalls: 'Total Calls',
      completedRides: 'Completed Rides',
      completedPercent: '{0}% of total',
      cancelledRides: 'Cancelled Rides',
      activeRides: 'Active Rides',
      avgFare: 'Avg fare {0}',
      operatorPerformance: 'Operator Performance',
      operator: 'Operator',
      shift: 'Shift',
      ridesCreated: 'Rides Created',
      active: 'active',
      morning: 'Morning',
      noOperators: 'No operators yet',
    },
    operators: {
      title: 'Operators Management',
      subtitle: 'Manage call center operators and track performance',
      searchPlaceholder: 'Search by name, email, or phone...',
      addButton: 'Add Operator',
      viewDetails: 'View Details',
      noOperators: 'No operators found matching your criteria',
    },
    rides: {
      title: 'Ride History',
      subtitle: 'View and manage all ride records',
      searchPlaceholder: 'Search by Ride ID, Customer, Location...',
      filterStatus: 'Filter by Status',
      allStatus: 'All Status',
      pendingStatus: 'Pending',
      assignedStatus: 'Assigned',
      acceptedStatus: 'Accepted',
      driverArrivingStatus: 'Driver Arriving',
      inProgressStatus: 'In Progress',
      completedStatus: 'Completed',
      cancelledStatus: 'Cancelled',
      expiredStatus: 'Expired',
      addRide: 'New Ride',
      createRide: 'Create New Ride',
      rideCreated: 'Ride created successfully!',
      customerName: 'Customer Name',
      customerPhone: 'Customer Phone',
      pickupLocation: 'Pickup Location',
      dropoffLocation: 'Dropoff Location',
      rideDetails: 'Ride Details',
      rideNotFound: 'Ride not found',
      backToDashboard: 'Back to Dashboard',
      rideProgress: 'Ride Progress',
      rideTitle: 'Ride #{0}',
      driverInformation: 'Driver Information',
      rideID: 'Ride ID',
      createdAt: 'Created At',
      lastUpdated: 'Last Updated',
      estimatedFare: 'Estimated Fare',
      cancelRide: 'Cancel Ride',
      noDriverAssigned: 'No driver assigned yet',
      liveTrackingPlaceholder: 'Live map tracking will be displayed here when Google Maps API is configured',
      carDetails: 'Vehicle Details',
      vehicleInfo: 'Vehicle Information',
      licensePlate: 'License Plate',
      customerInformation: 'Customer Information',
      name: 'Name',
      phoneNumber: 'Phone Number',
      pickup: 'Pickup',
      destination: 'Destination',
      driverName: 'Driver Name',
      vehicle: 'Vehicle',
      callDriver: 'Call Driver',
      liveTracking: 'Live Tracking',
      rideIdLabel: 'Ride ID',
      updated: 'Updated',
      roadDistance: 'Road distance',
      finalFare: 'Final Fare',
      fare: 'Fare',
    },
    coupons: {
      title: 'Coupon Management',
      subtitle: 'Manage driver coupon balances and transactions',
      selectDriver: 'Select Driver:',
      refill: 'Refill Coupons',
      confirmRefill: 'Confirm Refill',
      currentBalance: 'Current Coupon Balance',
      lowBalance: 'Low Balance Warning',
      moderateBalance: 'Moderate Balance',
      goodBalance: 'Good Balance',
      transactionHistory: 'Transaction History',
      noTransactions: 'No transactions found for this driver',
      enterAmount: 'Enter number of coupons',
      validAmount: 'Please enter a valid amount',
    },
    settings: {
      title: 'Settings',
      subtitle: 'Manage your account and application preferences',
      profileSettings: 'Profile Settings',
      notificationSettings: 'Notification Settings',
      systemSettings: 'System Settings',
      security: 'Security',
      autoAssign: 'Auto-assign Closest Driver',
      soundAlerts: 'Sound Alerts',
      mapKey: 'Google Maps API Key',
      saveSystem: 'Save System Settings',
      changePassword: 'Change Password',
      logout: 'Logout',
    },
  },
  am: {
    nav: {
      dashboard: 'ዳሽቦርድ',
      analytics: 'ትንታኔ',
      operators: 'ኦፕሬተሮች',
      callLogs: 'የጥሪ መዝገቦች',
      rides: 'ጉዞዎች',
      drivers: 'አሽከርካሪዎች',
      coupons: 'ኩፖኖች',
      settings: 'ቅንብሮች',
    },
    auth: {
      welcome: 'ወደ TEKUMMA እንኳን በደህና መጡ',
      description: 'ለዲስፓች ስርዓት መዳረሻ ይግቡ',
      login: 'ግባ',
      loggingIn: 'በመግባት ላይ...',
      operator: 'ኦፕሬተር',
      admin: 'አስተዳደር',
      email: 'ኢሜል',
      password: 'የሚከተለው ቃል',
      selectRole: 'እንደ ማን ትግቡ',
      fillAll: 'እባክዎ ሁሉንም ይሙሉ',
      loginSuccessful: 'በተሳካነት ወደ ደረጃው ገባ',
      code: 'የማረጋገጫ ኮድ',
      verify: 'አረጋግጥ',
      verifying: 'በማረጋገጥ ላይ...',
      backToSignIn: '← ወደ መግቢያ ተመለስ',
      twoFactorPrompt: 'የሁለት-ደረጃ ማረጋገጫ ኮድዎን ያስገቡ',
      invalidCode: 'ልክ ያልሆነ ኮድ — እንደገና ይሞክሩ።',
      enterCode: 'ከማረጋገጫ መተግበሪያዎ የ6-አሃዝ ኮድ ያስገቡ።',
    },
    common: {
      logout: 'ውጣ',
      notifications: 'ማስጠንቀቂያዎች',
      profile: 'መገለጫ',
      account: 'የእኔ መለያ',
      viewDetails: 'ዝርዝር ተመልከት',
      saveChanges: 'ለውጦችን አስቀመጥ',
      cancel: 'አቁም',
      addNew: 'አዲስ ያክሉ',
      search: 'ፈልግ',
      language: 'ቋንቋ',
      theme: 'ቅጥ',
      darkMode: 'ጨለማ ሁኔታ',
      lightMode: 'ብርሃን ሁኔታ',
    },
    drivers: {
      title: 'የአነሶች አስተዳደር',
      subtitle: 'የአነሶች ጉዞ አስተዳደር ያስተካክሉ',
      searchPlaceholder: 'በስም, ስልክ, ተሽከርካሪ, መዝገበ መኪና ፈልግ...',
      addButton: 'አዲስ አነስ ያክሉ',
      addTitle: 'አዲስ አነስ ያክሉ',
      save: 'አነሱን ያክሉ',
      edit: 'አንሱን አስተካክሉ',
      update: 'አስተካክል',
      viewProfile: 'መገለጫ ይመልከቱ',
      editSuccess: 'አነሱ በተሳካ ሁኔታ ተሻሽሏል!',
      createSuccess: 'አነሱ ተጨምሯል!',
      fillFields: 'እባክዎ ያስፈልጉትን ሁሉ ይሙሉ',
      driverName: 'የአነሱ ስም',
      phone: 'የስልክ ቁጥር',
      vehicle: 'የተሽከርካሪ ሞዴል',
      licensePlate: 'የፈቃድ ታስሪ',
      couponBalance: 'የኩፖን ዕረፍት',
      totalDrivers: 'አጠቃላይ አነሶች',
      available: 'የሚገኝ',
      busy: 'ሙሉ ስራ',
      noDrivers: 'አነሶች አልተገኙም',
    },
    analytics: {
      title: 'ተንተና እና ሪፖርቶች',
      subtitle: 'አጠቃላይ የጥሪ እና የጉዞ ስርጭት አፈፃፀም',
      today: 'ዛሬ',
      week: 'ይህ ሳምንት',
      month: 'ይህ ወር',
      year: 'ይህ ዓመት',
      totalRides: 'ጠቅላላ ጉዞዎች',
      totalRevenue: 'ጠቅላላ ገቢ',
      activeDrivers: 'ንቁ አሽከርካሪዎች',
      totalCalls: 'ጠቅላላ ጥሪዎች',
      completedRides: 'የተጠናቀቁ ጉዞዎች',
      completedPercent: 'ከጠቅላላው {0}%',
      cancelledRides: 'የተሰረዙ ጉዞዎች',
      activeRides: 'ንቁ ጉዞዎች',
      avgFare: 'አማካይ ክፍያ {0}',
      operatorPerformance: 'የኦፐሬተሮች አፈፃፀም',
      operator: 'ኦፐሬተር',
      status: 'ሁኔታ',
      shift: 'የስራ ፈርም',
      ridesCreated: 'የተፈጠሩ ጉዞዎች',
      active: 'ንቁ / ስራ ላይ',
      morning: 'ጧት',
      noOperators: 'እስካሁን ምንም ኦፐሬተር የለም',
    },
    operators: {
      title: 'የኦፐሬተሮች አስተዳደር',
      subtitle: 'የጥሪ ማዕከል ኦፐሬተሮችን ያስተዳድሩ እና አፈፃፀምን ይከታተሉ',
      searchPlaceholder: 'በስም፣ በኢሜይል ወይም በስልክ ፈልግ...',
      addButton: 'ኦፐሬተር ጨምር',
      viewDetails: 'ዝርዝር እይ',
      noOperators: 'ምንም የተገኘ ኦፐሬተር የለም',
      totalOperators: 'ጠቅላላ ኦፐሬተሮች',
      onlineNow: 'አሁን መስመር ላይ ያሉ',
      totalRidesCreated: 'የተፈጠሩ ጠቅላላ ጉዞዎች',
      totalCalls: 'ጠቅላላ ጥሪዎች',
      addNewTitle: 'አዲስ ኦፐሬተር ጨምር',
      addNewDescription: 'አዲስ የጥሪ ማዕከል ኦፐሬተር ወደ ስርዓቱ ያስገቡ',
      fullName: 'ሙሉ ስም',
      email: 'ኢሜይል',
      phone: 'የስልክ ቁጥር',
      password: 'የይለፍ ቃል',
      shift: 'የስራ ፈቃድ / ፈShift',
      morning: 'ጧት',
      cancel: 'ሰርዝ / ተመለስ',
      addOperator: 'ኦፐሬተር ጨምር',
      active: 'ንቁ',
      inactive: 'አልተነቃቁም',
    },
    rides: {
      title: 'ጉዞዎች',
      subtitle: 'ሁሉንም የጉዞ መዝገቦች ይመልከቱ እና ያስተዳድሩ',
      searchPlaceholder: 'በጉዞ መለያ (Ride ID)፣ በደንበኛ፣ በአሽከርካሪ ፈልግ...',
      filterStatus: 'በሁኔታ ይጣሩ',
      allStatus: 'ሁሉም ሁኔታዎች',
      pendingStatus: 'በሂደት ላይ ያለ',
      assignedStatus: 'የተመደበ',
      acceptedStatus: 'የተቀበለው',
      driverArrivingStatus: 'አሽከርካሪው እየደረሰ ነው',
      inProgressStatus: 'በጉዞ ላይ ያለ',
      completedStatus: 'የተጠናቀቀ',
      cancelledStatus: 'የተሰረዘ',
      expiredStatus: 'ጊዜው ያለፈበት',
      addRide: 'አዲስ ጉዞ',
      createRide: 'አዲስ ጉዞ ፍጠር',
      rideCreated: 'ጉዞ በተሳካ ሁኔታ ተፈጥሯል!',
      customerName: 'የደንበኛ ስም',
      customerPhone: 'የደንበኛ ስልክ',
      pickupLocation: 'መነሻ ቦታ',
      dropoffLocation: 'መድረሻ ቦታ',
      rideDetails: 'የጉዞ ዝርዝር',
      rideNotFound: 'ጉዞ አልተገኘም',
      backToDashboard: 'ወደ ዳሽቦርድ ተመለስ',
      rideProgress: 'የጉዞ ሂደት',
      rideTitle: 'ጉዞ #{0}',
      driverInformation: 'የአሽከርካሪ መረጃ',
      rideID: 'የጉዞ መለያ',
      createdAt: 'የተፈጠረበት',
      lastUpdated: 'መጨረሻ የተሻሻለበት',
      estimatedFare: 'ተገምቶ የሚከፈል ክፍያ',
      cancelRide: 'ጉዞ ሰርዝ',
      noDriverAssigned: 'አሽከርካሪ አልተመደበም',
      liveTrackingPlaceholder: 'የቀጥታ ካርታ ከGoogle Maps API ጋር ሲዋቀር እዚህ ይታያል',
      carDetails: 'የተሽከርካሪ ዝርዝር',
      vehicleInfo: 'የተሽከርካሪ መረጃ',
      customerInformation: 'የደንበኛ መረጃ',
      name: 'ስም',
      phoneNumber: 'የስልክ ቁጥር',
      pickup: 'መነሻ ቦታ',
      destination: 'መድረሻ',
      driverName: 'የአሽከርካሪ ስም',
      vehicle: 'ተሽከርካሪ',
      callDriver: 'አሽከርካሪ ይደውሉ',
      liveTracking: 'የቀጥታ ክትትል',
      rideIdLabel: 'የጉዞ መለያ',
      updated: 'የተሻሻለ',
      roadDistance: 'የመንገድ ርቀት',
      finalFare: 'የመጨረሻ ክፍያ',
      fare: 'ክፍያ',
      rideId: 'የጉዞ መለያ',
      customer: 'ደንበኛ',
      dropoff: 'መድረሻ ቦታ',
      driver: 'አሽከርካሪ',
      status: 'ሁኔታ',
      time: 'ሰዓት',
      actions: 'እርምጃዎች',
      noRides: 'ምንም የተገኘ ጉዞ የለም',
      showingCount: 'ከ {1} ጉዞዎች ውስጥ {0} እያሳየ ነው',
      previous: 'የቀደመው',
      next: 'ቀጣይ',
      track: 'ተከታተል',
      reNotifyNearby: 'አስተገባቸውን ለአሽከርካሪዎች ድጋሚ ላክ',
      notAssigned: 'ያልተመደበ',
      newRide: 'አዲስ ጉዞ',
    },
    coupons: {
      title: 'የኩፖን አስተዳደር',
      subtitle: 'የአሽከርካሪዎችን የኩፖን ቀሪ ሂሳብ ያስተዳድሩ',
      selectDriver: 'አሽከርካሪ ይምረጡ:',
      refill: 'ኩፖን ሙላ',
      confirmRefill: 'መሙላቱን አረጋግጥ',
      currentBalance: 'የአሁኑ ቀሪ ሂሳብ',
      lowBalance: 'ዝቅተኛ ቀሪ ሂሳብ ማስጠንቀቂያ',
      moderateBalance: 'መካከለኛ ቀሪ ሂሳብ',
      goodBalance: 'ጥሩ ቀሪ ሂሳብ',
      transactionHistory: 'የግብይት ታሪክ',
      noTransactions: 'ለዚህ አሽከርካሪ ምንም ግብይት አልተገኘም',
      enterAmount: 'የኩፖን ብዛት ያስገቡ',
      validAmount: 'እባክዎ ትክክለኛ መጠን ያስገቡ',
      totalDrivers: 'ጠቅላላ አሽከርካሪዎች',
      totalCoupons: 'ጠቅላላ ኩፖኖች',
      lowBalanceCount: 'ዝቅተኛ ቀሪ ሂሳብ',
      searchPlaceholder: 'በስም፣ በሰሌዳ ቁጥር ወይም በስልክ ፈልግ...',
      refillTitle: 'ኩፖን ሙላ — {0}',
      phone: 'የስልክ ቁጥር',
      plate: 'የሰሌዳ ቁጥር',
      status: 'ሁኔታ',
      amountToAdd: 'የሚጨመረው መጠን',
      placeholder: 'የኩፖን ብዛት ያስገቡ',
      newBalance: 'አዲስ ቀሪ ሂሳብ',
      good: 'ጥሩ',
      moderate: 'መካከለኛ',
      low: 'ዝቅተኛ',
      couponBalance: 'የኩፖን ቀሪ ሂሳብ',
      noDrivers: 'ምንም አሽከርካሪ አልተገኘም',
    },
    settings: {
      title: 'ማስተካከያዎች',
      subtitle: 'የመለያዎን እና የቶኩማ ስርዓት ውቅሮችን ያስተዳድሩ',
      profileSettings: 'ፕሮፋይል ቅንብሮች',
      notificationSettings: 'የማስጠንቀቂያ ቅንብሮች',
      systemSettings: 'የስርዓት ቅንብሮች',
      security: 'ደህንነት',
      autoAssign: 'በአቅራቢያ ያለውን አሽከርካሪ በራስ-መደብ',
      soundAlerts: 'የድምጽ ማስጠንቀቂያዎች',
      mapKey: 'የGoogle Maps API ቁልፍ',
      saveSystem: 'የስርዓት ቅንብሮችን አስቀምጥ',
      changePassword: 'የይለፍ ቃል ቀይር',
      logout: 'ውጣ',
      profile: 'ፕሮፋይል',
      yourAccountInfo: 'የመለያዎ መረጃ',
      name: 'ስም',
      role: 'ሚና',
      administrator: 'አስተዳዳሪ (Administrator)',
      email: 'ኢሜይል',
      pricingDispatchCommission: 'ዋጋ፣ ማሰራጨት እና ኮሚሽን',
      businessRules: 'የቶኩማ የንግድ ህጎች (Live)',
      baseFare: 'የመነሻ ክፍያ (ETB)',
      perKm: 'በኪሎሜትር (ETB)',
      timeBlockCharge: 'የጊዜ ብሎክ ክፍያ (ETB)',
      timeBlockMinutes: 'የጊዜ ብሎክ (በደቂቃ)',
      minimumFare: 'አነስተኛ የጉዞ ክፍያ (ETB)',
      dispatchRadius: 'የጥሪ ስርጭት ራዲየስ (km)',
      maxDriversNotified: 'ከፍተኛው የማሳወቂያ አሽከርካሪዎች ብዛት',
      offerTimeout: 'የጥሪ ማብቂያ ጊዜ (በሰከንድ)',
      minCouponBalance: 'አነስተኛ የኩፖን ቀሪ ሂሳብ',
      defaultCommission: 'መደበኛ ኮሚሽን (%)',
      saveSettings: 'ለውጦችን አስቀምጥ',
      callCenter: 'የጥሪ ማዕከል',
      readOnly: 'ተነባቢ-ብቻ — ለማስተካከል የአስተዳዳር መዳረሻ ያስፈልጋል',
    },
  },
  om: {
    nav: {
      dashboard: 'Boordii',
      analytics: 'Xiinxala',
      operators: 'Opeeretaroota',
      callLogs: 'Galmee Bilbilaa',
      rides: 'Imala',
      drivers: 'Draayivaroota',
      coupons: 'Kuuponoota',
      settings: "Qindaa'inaa",
    },
    auth: {
      welcome: 'TEKUMMA keessa baga nagaan dhuftan',
      description: 'Sirna geejjibaa fayyadamuu dhaaf seenaa',
      login: 'Seeni',
      loggingIn: 'Seenaa jira...',
      operator: 'Opeeretara',
      admin: 'Bulchaa',
      email: 'Emeelii',
      password: 'Jecha Darbiinsaa',
      selectRole: 'Akka eenyutti seentuu filadhu',
      fillAll: 'Dirreelee hundumaa guuti',
      loginSuccessful: 'Milkaawinaan seentee jirta',
      code: 'Koodii Mirkaneessaa',
      verify: 'Mirkaneessi',
      verifying: 'Mirkaneessaa jira...',
      backToSignIn: '← Gara seenuutti deebiʼi',
      twoFactorPrompt: 'Koodii mirkaneessaa waliigalaa lamaffaa keessan galchaa',
      invalidCode: 'Koodiin sirrii miti — irra deebiʼii yaali.',
      enterCode: 'Koodii lakkoofsa 6 app mirkaneessaa keessan irraa galchaa.',
    },
    common: {
      logout: 'Bahi',
      notifications: 'Beeksisoota',
      profile: 'Porofaayilii',
      account: 'Akaawuntii Koo',
      viewDetails: "Bal'inaan Ilaali",
      saveChanges: "Jijjiirraa Olkaa'i",
      cancel: 'Haqi',
      addNew: 'Haaraa Dabali',
      search: 'Barbaadi',
      language: 'Afaan',
      theme: 'Bifuma',
      darkMode: 'Haala Dukkanaa',
      lightMode: 'Haala Iftaa',
      name: 'Maqaa',
      phone: 'Lakkoofsa Bilbilaa',
      email: 'Emeelii',
      status: 'Haala',
      actions: 'Tarkaanfiiwwan',
      noResults: 'Waan argame hin jiru',
      loading: "Fe'amaa jira...",
      back: "Deebi'i",
      save: "Olkaa'i",
      edit: 'Gulaali',
      delete: 'Haqi',
      confirm: 'Mirkaneessi',
      role: 'Gahee',
      callCenter: 'Wiirtuu Bilbilaa',
    },
    dashboard: {
      newRide: 'Imala Haaraa',
      logCall: 'Bilbila Galmeessi',
      pendingRides: 'Imala Eeggamaa Jiraan',
      activeRides: 'Imala Socho-aa',
      noPendingRides: 'Imala eeggamaa jiru hin jiru',
      noActiveRides: 'Imala socho-aa hin jiru',
      driverStatus: 'Haala Draayivarootaa',
      available: 'Qophii',
      busy: 'Bishi',
      offline: 'Cufaa',
      assignDriver: 'Draayivara Ramadi',
      assignTo: 'Draayivara Ramadi — ',
      noAvailableDrivers: 'Draayivara qophii jiru hin jiru',
      renotifyDrivers: 'Draayivarootaaf Ammas Ergi',
      track: 'Hordofi',
      assign: 'Ramadi',
      viewDetails: "Bal'inaan Ilaali",
      coupon: 'Kuuponii',
    },
    drivers: {
      title: 'Bulchiinsa Draayivaroota',
      subtitle: 'Tarree draayivaroota keessanii bulchaa',
      searchPlaceholder: 'Maqaa, bilbila, konkolaataa, gabatee konkolaataan barbaadi...',
      addButton: 'Draayivara Haaraa Dabali',
      addTitle: 'Draayivara Haaraa Dabali',
      save: 'Draayivara Dabali',
      edit: 'Draayivara Gulaali',
      update: 'Haaromsi',
      viewProfile: 'Porofaayilii Ilaali',
      editSuccess: 'Draayivarri milkaawinaan haaromfame!',
      createSuccess: 'Draayivarri milkaawinaan dabalame!',
      fillFields: 'Maqaa, bilbila, emeelii, gabatee fi lakkoofsa heyyamaa barbaachisaadha',
      driverName: 'Maqaa Draayivaraa',
      fullName: 'Maqaa Guutuu',
      phone: 'Bilbila',
      vehicle: 'Moodela Konkolaataa',
      vehicleType: 'Gosa Konkolaataa',
      licensePlate: 'Gabatee Lakkoofsa Konkolaataa',
      licenseNumber: 'Lakkoofsa Heyyama Konkolaachisummaa',
      couponBalance: 'Madaallii Kuuponii Jalqabaa',
      totalDrivers: 'Waliigala Draayivaroota',
      available: 'Qophii',
      busy: 'Bishi',
      noDrivers: 'Draayivarri tokkollee hin argamne',
      commission: 'Komishinii Idilee (%)',
    },
    operators: {
      title: 'Bulchiinsa Opeeretaroota',
      subtitle: "Opeeretaroota Wiirtuu Bilbilaa Bulchi fi Ga'umsa Isaanii Hordofi",
      searchPlaceholder: 'Maqaa, emeelii, ykn bilbilaan barbaadi...',
      addButton: 'Opeeretara Dabalata Uumi',
      addTitle: 'Opeeretara Haaraa Dabali',
      addDescription: 'Opeeretara wiirtuu bilbilaa haaraa sirna keessatti dabali',
      viewDetails: "Bal'inaan Ilaali",
      noOperators: 'Opeeretarri tokkollee hin argamne',
      totalOperators: 'Waliigala Opeeretaroota',
      onlineNow: 'Amma Intarneetii Irra Jiru',
      totalRidesCreated: 'Waliigala Imala Uumame',
      totalCalls: 'Waliigala Bilbilaa',
      ridesCreated: 'Imala Uumame',
      fullName: 'Maqaa Guutuu',
      password: 'Jecha Darbiinsaa',
      shift: 'Dabare',
      morning: 'Ganama',
      afternoon: 'Waaree Booda',
      night: 'Halkan',
      active: 'Socho-aa',
      inactive: 'Hin Socho-in',
    },
    rides: {
      title: 'Seenaa Imalaa',
      subtitle: 'Galmee imala hundumaa ilaali fi bulchi',
      searchPlaceholder: 'Eenyummeessaa Imalaa (Ride ID), Maamila, Draayivaraan barbaadi...',
      filterStatus: 'Haala Filadhu',
      allStatus: 'Haala Hundumaa',
      pending: 'Eeggamaa',
      assigned: 'Ramadame',
      accepted: 'Fudhataame',
      driverArriving: 'Draayivarri dhufaa jira',
      inProgress: 'Deemaa Jira',
      completed: 'Xumurame',
      cancelled: 'Haqame',
      expired: 'Yeroon Darbee',
      addRide: 'Imala Haaraa',
      createRide: 'Imala Haaraa Uumi',
      rideCreated: 'Imalli uumame — draayivaroota dhiyoo jiraniif ergame',
      customerName: 'Maqaa Maamila',
      customerPhone: 'Bilbila Maamila',
      pickupLocation: "Ka'umsa",
      dropoffLocation: "Ga'umsa",
      rideDetails: "Bal'ina Imalaa",
      rideNotFound: 'Imalli hin argamne',
      backToRides: "Gara Imalatti Deebi'i",
      rideProgress: 'Guddina Imalaa',
      driverInformation: 'Odeeffannoo Draayivaraa',
      customerInformation: 'Odeeffannoo Maamila',
      rideID: 'ID Imalaa',
      createdAt: 'Yeroo Uumame',
      lastUpdated: 'Yeroo Haaromfame',
      fare: 'Gatii Imalaa',
      finalFare: 'Gatii Xumuraa',
      distance: 'Fageenya',
      cancelRide: 'Imala Haqi',
      noDriverAssigned: 'Draayivarri hin ramadamne',
      notAssigned: 'Ramaddii Malee',
      licensePlate: 'Gabatee Lakkoofsa',
      liveTracking: 'Hordoffii Kallattii',
      showing: 'Agarsiisaa jira',
      of: 'keessaa',
      previous: 'Kan Duraa',
      next: 'Kan Antaa',
      rideId: 'ID Imalaa',
      customer: 'Maamila',
      pickup: "Ka'umsa",
      dropoff: "Ga'umsa",
      driver: 'Draayivara',
      time: 'Yeroo',
      actions: 'Tarkaanfiiwwan',
      noRides: 'Imalli tokkollee hin argamne',
      destination: "Ga'umsa",
      phoneNumber: 'Lakkoofsa Bilbilaa',
      driverName: 'Maqaa Draayivaraa',
      vehicle: 'Konkolaataa',
      callDriver: 'Draayivara Bilbili',
      trackRide: 'Imala kallattiin hordofi',
    },
    coupons: {
      title: 'Bulchiinsa Kuuponii',
      subtitle: 'Madaallii kuuponii draayivarootaa bulchi',
      searchPlaceholder: 'Maqaa, lakkoofsa gabatee, ykn bilbilaan barbaadi...',
      refill: 'Kuuponii Guuti',
      confirmRefill: 'Guutuu Mirkaneessi',
      currentBalance: 'Madaallii Kuuponii',
      lowBalance: 'Madaallii Gad-aanaa',
      low: 'Gad-aanaa',
      moderate: 'Giddugaleessa',
      moderateBalance: 'Madaallii Giddugaleessa',
      good: 'Gaarii',
      goodBalance: 'Madaallii Gaarii',
      noDrivers: 'Draayivarri tokkollee hin argamne',
      totalDrivers: 'Waliigala Draayivaroota',
      totalCoupons: 'Waliigala Kuuponoota',
      lowBalanceCount: 'Madaallii Gad-aanaa',
      enterAmount: 'Lakkoofsa kuuponii galchi',
      amountToAdd: "Baay'ina Dabalamuu",
      newBalance: 'Madaallii Haaraa',
      currentBalanceLabel: 'Madaallii Ammaa',
      plateLabel: 'Gabatee Lakkoofsa',
      coupons: 'kuuponii',
    },
    callLogs: {
      title: 'Galmee Bilbilaa',
      subtitle: 'Seenaa tarreeffama bilbila maamiltootaa',
      searchPlaceholder: 'Maamila, bilbila, ykn opeeretaraan barbaadi...',
      logCall: 'Bilbila Galmeessi',
      logTitle: 'Bilbila Galmeessi',
      totalCalls: 'Waliigala Bilbilaa',
      completed: 'Xumurame',
      missed: 'Dagatame',
      avgDuration: 'Turtii Giddugaleessa',
      callHistory: 'Seenaa Bilbilaa',
      time: 'Yeroo',
      customer: 'Maamila',
      phone: 'Bilbila',
      operator: 'Opeeretara',
      status: 'Haala',
      duration: 'Turtii',
      rideId: 'ID Imalaa',
      notes: 'Yaadannoo',
      noLogs: 'Galmeen bilbilaa tokkollee hin argamne',
      allStatus: 'Haala Hundumaa',
      abandoned: 'Dhiifame',
      customerPhone: 'Bilbila Maamila',
      customerName: 'Maqaa Maamila',
      durationMinutes: 'Turtii (Daqiiqaa)',
      outcome: "Bu'aa",
      saveCall: "Bilbila Olkaa'i",
    },
    analytics: {
      title: 'Xiinxala fi Gabaasota',
      subtitle: 'Waliigala raawwii geejjiba',
      today: "Har'aa",
      thisWeek: 'Torbee Kana',
      thisMonth: "Ji'a Kana",
      thisYear: 'Waggaa Kana',
      totalRides: 'Waliigala Imalaa',
      totalRevenue: 'Galii Waliigalaa',
      activeDrivers: 'Draayivaroota Socho-aa',
      completedRides: 'Imala Xumurame',
      cancelledRides: 'Imala Haqame',
      activeRides: 'Imala Socho-aa',
      avgFare: 'Gatii Giddugaleessa',
      ofTotal: '% waliigalaa',
      operatorPerformance: "Ga'umsa Opeeretaraa",
      noOperators: 'Opeeretarri ammaaf hin jiru',
      shift: 'Dabare',
      ridesCreated: 'Imala Uumame',
      totalCalls: 'Waliigala Bilbilaa',
    },
    settings: {
      title: "Qindaa'inaa",
      subtitle: "Akaawuntii keessaniif qindaa'ina sirna Tokuma bulchaa",
      profile: 'Porofaayilii',
      profileDescription: 'Odeeffannoo akaawuntii keessanii',
      pricingTitle: 'Gatii, Ergaa & Komishinii',
      pricingDescription: 'Seera Hojii Tokuma Kallattiin',
      pricingReadOnly: '(dubbisuu qofa — jijjiiruu kan dandayu bulchaa qofa)',
      saveSystem: "Qindaa'ina Sirna Olkaa'i",
      systemSaved: "Qindaa'inni sirna olkaayame",
      adminOnly: 'Bulchaan qofa jijjiiruu dandaya',
      name: 'Maqaa',
      role: 'Gahee',
      admin: 'Bulchaa',
      callCenter: 'Wiirtuu Bilbilaa',
    },
    employeeProfile: {
      driver: 'Draayivara',
      profile: 'Porofaayilii',
      details: "Bal'ina",
      email: 'Emeelii',
      status: 'Haala',
      couponBalance: 'Madaallii Kuuponii',
      coupons: 'kuuponii',
      vehicleType: 'Gosa Konkolaataa',
      vehicleModel: 'Moodela Konkolaataa',
      licensePlate: 'Gabatee Lakkoofsa',
      licenseNumber: 'Lakkoofsa Heyyama',
      rating: 'Madaallii',
      completedRides: 'Imala Xumurame',
      lastLocation: 'Bakka Dhumaa',
      commission: 'Komishinii Tokuma',
      manageCoupons: 'Kuuponii Bulchi',
      notFound: 'Draayivarri hin argamne',
      backToDrivers: "Gara Draayivarootti Deebi'i",
    },
  },
};

type TranslationKey = keyof typeof translations['en'];

interface AppContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  theme: ThemeMode;
  setTheme: (theme: ThemeMode) => void;
  t: (path: string, fallback?: string, params?: Record<string, string | number>) => string;
}

const AppContext = createContext<AppContextValue | undefined>(undefined);

const interpolateString = (value: string, params?: Record<string, string | number>) => {
  if (!params) return value;
  return value.replace(/\{([^}]+)\}/g, (_, key: string) => String(params[key] ?? `{${key}}`));
};

const getString = (lang: Language, path: string, fallback?: string, params?: Record<string, string | number>) => {
  const keys = path.split('.');
  let current: any = translations[lang];

  for (const key of keys) {
    if (current?.[key] == null) {
      return interpolateString(fallback ?? path, params);
    }
    current = current[key];
  }

  return interpolateString(typeof current === 'string' ? current : fallback ?? path, params);
};

export function AppProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');
  const [theme, setTheme] = useState<ThemeMode>('light');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    const savedTheme = localStorage.getItem('theme') as ThemeMode;

    if (savedLanguage && ['en', 'am', 'om'].includes(savedLanguage)) {
      setLanguage(savedLanguage);
    }

    if (savedTheme === 'dark' || savedTheme === 'light') {
      setTheme(savedTheme);
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  useEffect(() => {
    localStorage.setItem('theme', theme);
    if (theme === 'dark') {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [theme]);

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      theme,
      setTheme,
      t: (path: string, fallback?: string, params?: Record<string, string | number>) => getString(language, path, fallback, params),
    }),
    [language, theme]
  );

  return <AppContext.Provider value={value}>{children}</AppContext.Provider>;
}

export function useAppContext() {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useAppContext must be used within AppProvider');
  }
  return context;
}
